[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.2"
anyhow = "1.0.75"
arrayvec = "0.7.4"
itertools = "0.12.0"
num-integer = "0.1.45"
rand = "0.8.5"
rustc-hash = "1.1.0"

[profile.release]
lto = true
